# Production config
#
# Site settings
title: "Ronan Guilbault"
subtitle: "Mon site"
email: "ronan.guilbault@gmail.com"
description: "Lorem ipsum dolor sit amet"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rguilbault.github.io"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
highlighter: rouge
